packages/api/src/batch/batch.controller.ts, packages/api/src/batch/batch.module.ts, packages/api/src/batch/batch.service.ts, packages/api/src/batch/batchAmount.dto.ts, packages/api/src/transfer/transfer.service.ts
This PR introduces a new API endpoint `/batchs/:batchNumber/:gateway` for calculating the total amount of withdrawal transactions for a given `batchNumber` and `gateway`.
The motivation behind this change is to offer more detailed analytics and reporting capabilities for users and systems interfacing with our service.
=> feat: add /batchs/:batch/:gateway api

packages/app/src/App.vue
Delete ending our support of Goerli testnet
Now using Goerli testnet
=> fix:delete ending our support of Goerli testnet

packages/app/src/components/token/TokenListTable.vue
Fix UI style of Tokens page,Vertical centering of text.
styles error
=> fix:Fix UI style of Tokens page

packages/app/src/components/header/TheHeader.vue, packages/app/src/components/token/TokenListTable.vue, packages/app/src/locales/en.json
Fix the icon style of FROM CHAIN
=> Tokens/fix the icon style of FROM CHAIN

packages/app/src/components/header/TheHeader.vue
Modify header logo jump to Navo
=> modify: Header logo jump to Navo

packages/data-fetcher/src/transfer/extractHandlers/finalizeDeposit/default.handler.ts
=> feat: add todo text

packages/app/index.html
=> Feature hotfix og image

packages/event-watcher/events.mainnet.json, packages/event-watcher/events.mainnet2.json
Update contractDeploymentBlock
=> Sarah shy0920 patch 1

packages/app/src/components/token/TokenListTable.vue, packages/app/src/composables/useEnvironmentConfig.ts, packages/app/src/configs/goerli.config.json, packages/app/src/configs/index.ts, packages/app/src/configs/nova.config.json, packages/app/src/utils/constants.ts
=> fix:tokens:add fromChain name

.gitignore, packages/app/package.json, packages/app/src/components/AddressLink.vue, packages/app/src/components/common/table/fields/TokenTVL.vue, packages/app/src/components/token/TokenListTable.vue, packages/app/src/configs/networkKey.ts, packages/app/src/types.ts
=> feat: add tokens tvl address

packages/app/src/components/AddressLink.vue
=> fix: address link

packages/app/src/components/token/TokenListTable.vue, packages/app/src/utils/constants.ts
=> feat: Hide all zero addresses

packages/app/src/composables/common/Api.d.ts, packages/app/src/composables/useTokenLibrary.ts, packages/app/src/views/TokensView.vue
=> feat: tokens:sort by TVL

packages/app/src/components/header/TheHeader.vue
modify:  header logo jump to Home page
=> modify: Header logo jump to Home

packages/app/src/components/token/TokenListTable.vue
fix:Tokens:table loading style
=> fix:Tokens:table loading style

packages/worker/extraCoinsList.json
=> Add blast ezETH & Arbitrum rsETH

packages/worker/extraCoinsList.json
=> Add base wstETH

packages/worker/extraCoinsList.json
=> Update mswETH & mstETH

packages/app/src/components/NetworkStats.vue, packages/app/src/components/common/table/Table.vue, packages/app/src/components/token/TokenListTable.vue, packages/app/src/locales/en.json
fix: tokens  moblile table name bug
@zkLinkLabs
=> Feature fix tokens tvl

packages/worker/README.md
=> add extraTokenAttributes.md

packages/worker/extraCoinsList.json
=> Update add mwBETH (wETH) & mmETH (mETH)

packages/worker/extraTokenAttributes.json
=> add mstETH, mswETH, mwBETH, mmETH

packages/worker/src/migrations/1711442817699-migrations.ts
- [done] Add a database script for updating tvlHistory.
=> add tvlHistory sql migration

packages/api/src/block/block.controller.ts
##when sql label is empty , the latest is undefined
-First, check if "latest" is undefined. If it is, the data is empty.
=> fix data table is empty

packages/api/src/token/token.controller.ts
#The calculation of the price needs to be more precise.
It should start from the non-zero digit
=> Fix price more precise#72

packages/worker/extraTokenAttributes.json
=> Add DAI in Base

packages/app/src/views/ChartView.vue
=> fix uaws chart front $

packages/app/src/views/ChartView.vue, packages/app/src/views/ChartsListView.vue
fix $ in UAW's chartList and chart views
=> fix $ in chartList

packages/worker/src/repositories/addressTransfer.repository.ts
=> fix uaw number,change sql

packages/worker/src/repositories/addressTransfer.repository.ts
just remove log and old sql query
=> remove old sql query and debug log

packages/worker/extraTokenAttributes.json
=> Update Nova Merged wBTC, USDC, USDT, DAI Logo

packages/worker/extraCoinsList.json
=> Update Nova Merged wBTC, USDT, USDC, DAI

packages/worker/extraCoinsList.json
=> Update change Nova Merged USDC

packages/app/src/configs/nova.config.json
Remove goerli option of From chain Options.
@zkcarter
=> HotFix: Tokens: remove goerli option of From chain Options.

packages/api/Dockerfile-dev, packages/api/Dockerfile-main, packages/api/Dockerfile-preview, packages/app/Dockerfile-dev, packages/app/Dockerfile-main, packages/app/Dockerfile-preview, packages/data-fetcher/Dockerfile-dev, packages/data-fetcher/Dockerfile-main, packages/data-fetcher/Dockerfile-preview, packages/event-watcher/Dockerfile-dev, packages/event-watcher/Dockerfile-main, packages/event-watcher/Dockerfile-preview, packages/worker/Dockerfile-dev, packages/worker/Dockerfile-main, packages/worker/Dockerfile-preview
=> add Dockerfiles

packages/api/src/token/token.service.ts, packages/worker/src/repositories/token.repository.ts
fix this #104 
found native token
=> tvl exclude native tokens

packages/api/Dockerfile-dev, packages/api/Dockerfile-main, packages/api/Dockerfile-preview, packages/app/Dockerfile, packages/app/Dockerfile-dev, packages/app/Dockerfile-main, packages/app/Dockerfile-preview, packages/data-fetcher/Dockerfile-dev, packages/data-fetcher/Dockerfile-main, packages/data-fetcher/Dockerfile-preview, packages/event-watcher/Dockerfile-dev, packages/event-watcher/Dockerfile-main, packages/event-watcher/Dockerfile-preview, packages/worker/Dockerfile-dev, packages/worker/Dockerfile-main, packages/worker/Dockerfile-preview
=> update build commands

packages/app/src/composables/useContractInteraction.ts
=> fix:contract: Wallet Estimating gas too high

packages/app/src/components/token/TableFilterModal.vue, packages/app/src/components/token/TokenListTable.vue, packages/app/src/views/TokensView.vue
=> feat:tokens:rollback:remove pagination

packages/data-fetcher/src/abis/L2ERC20Bridge.json, packages/data-fetcher/src/constants.ts, packages/data-fetcher/src/log/logType.ts, packages/data-fetcher/src/token/token.service.ts, packages/data-fetcher/src/transfer/extractHandlers/finalizeDeposit/depositMerge.handler.ts, packages/data-fetcher/src/transfer/extractHandlers/index.ts, packages/data-fetcher/src/transfer/transfer.service.ts
=> fix depositMerge event transferType is not depositMerge

packages/data-fetcher/src/abis/L2ERC20Bridge.json, packages/data-fetcher/src/constants.ts, packages/data-fetcher/src/log/logType.ts, packages/data-fetcher/src/token/token.service.ts, packages/data-fetcher/src/transfer/extractHandlers/finalizeDeposit/depositMerge.handler.ts, packages/data-fetcher/src/transfer/extractHandlers/index.ts, packages/data-fetcher/src/transfer/transfer.service.ts
=> Fix deposit merge event

packages/app/src/components/transactions/Table.vue, packages/app/src/composables/common/Api.d.ts, packages/app/src/composables/useTransaction.ts, packages/worker/scripts/updateNetworkKeyValue.ts
=> Feature tx form l1 chian

packages/app/src/components/AddressLink.vue, packages/app/src/components/transactions/Table.vue, packages/app/src/components/transactions/infoTable/TransferInfo.vue, packages/app/src/composables/useEnvironmentConfig.ts, packages/app/src/composables/useTransaction.ts, packages/app/src/configs/index.ts, packages/app/src/configs/nova.config.json
=> fix:tx l1chain tag and link bug

packages/worker/Dockerfile-dev, packages/worker/Dockerfile-main, packages/worker/Dockerfile-preview
=> polish cmd

packages/worker/extraTokenAttributes.json
=> Update USDT Logo

packages/worker/extraTokenAttributes.json
=> Add rnETH Logo

packages/worker/extraCoinsList.json
=> Add BTCT (inherent bitcoin price)

packages/worker/extraTokenAttributes.json
=> Add BTCT from Tron

packages/api/src/batch/batch.service.ts, packages/api/src/batch/batchRootEventLogs.entity.ts, packages/event-watcher/src/entities/batchRootEventLogs.entity.ts, packages/worker/src/entities/batchRootEventLogs.entity.ts, packages/worker/src/migrations/1715064911170-addEventLogsUniqueIndex.ts
when last block number - 64 has watched openRangeBatchRoot event , it will have duplicate data
=> Fix event duplicate data

packages/app/src/components/common/table/fields/ExcuteTxHashChain.vue
=> fix:ExcuteTXHashChin bug

packages/app/src/components/batches/InfoTable.vue, packages/app/src/components/common/table/fields/ExcuteTxHashChain.vue
fix:Display chain according to batchNumber
=> Feature fix excuted tx hash chian limit

packages/worker/extraTokenAttributes.json
=> Add uniETH-Manta

packages/worker/extraCoinsList.json
=> Add Manta uniETH

packages/worker/extraCoinsList.json
=> Revise uniETH

packages/worker/extraTokenAttributes.json
=> change solv BTC icon, add M-BTC icon

packages/worker/package.json, packages/worker/src/app.module.ts, packages/worker/src/values/dailyTransaction.service.ts
change the task from interval time to set time
=> Feature daily 7am task

packages/api/historyTokenList.json, packages/api/src/app.module.ts, packages/api/src/app.service.ts, packages/api/src/common/dtos/date.dto.ts, packages/api/src/configureApp.ts, packages/api/src/historyToken/historyToken.service.ts, packages/api/src/historyToken/worker.ts, packages/api/src/token/token.controller.ts, packages/api/src/token/token.dto.ts, packages/api/src/token/token.service.ts
every day 1am token will save a balance json where in historyTokenList.json
=> Featurn token balance history

packages/worker/extraTokenAttributes.json
=> Add BBUSD, BBTC, SolvBTC.b

packages/worker/extraCoinsList.json
=> Change UNI-ETH

packages/worker/extraCoinsList.json
=> add uniBTC (Ethereum)

packages/worker/extraTokenAttributes.json
=> Add UniBTC

packages/worker/extraCoinsList.json
=> Add Scroll tokens

packages/worker/extraCoinsList.json
=> change WBTC Ethereum & Arbitrum address to Extra & Extra2

packages/worker/extraTokenAttributes.json
=> Add_ZKL_Logo_From_Etherscan.json
